// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjwrconvdmonbpdyzqcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqd3Jjb252ZG1vbmJwZHl6cWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MzA0NDksImV4cCI6MjA3OTQwNjQ0OX0.BBTBwgGsKLFYwgqSit1aaCfXMkR2B8fAN55TufEikO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); 